spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

watson:
  speech-to-text:
    url: "https://api.eu-de.speech-to-text.watson.cloud.ibm.com/instances/a767c987-f49c-4717-98f3-df5a86beef6c/v1/recognize"
    api-key: "g3zIYUolm2Uz7uM7AubQfLq1CHW1af1E0tScC_YYyLCW"
  text-to-speech:
    url: "https://api.eu-de.text-to-speech.watson.cloud.ibm.com/instances/a431de8e-af04-40df-b177-fafc1979e0ef/v1/synthesize?voice=fr-CA_LouiseV3Voice"
    api-key: "JNpU6xiqSCEahMsq75Cuw8Dvgv1e8HFiHK2WVfZhGeJQ"
