watson:
  speech-to-text:
    url: "https://api.eu-de.speech-to-text.watson.cloud.ibm.com/instances/a767c987-f49c-4717-98f3-df5a86beef6c/v1/recognize"
    api-key: ""
  text-to-speech:
    url: "https://api.eu-de.text-to-speech.watson.cloud.ibm.com/instances/effe053c-f02a-4a39-8339-d6d181ef71fe/v1/synthesize?voice=en-US_AllisonV3Voice"
    api-key: ""
